task_1
brstu/OTIS-2023 pull request #1
Opened 2023-09-28 07:46 UTC by sosiska52

2023-09-28 08:24 UTC, Gomziakoff commented on trunk/ii02313/task_01/src/otis_1.cpp
зачем запоминать так много предыдущих значений y если можно возвращать их функцией

2023-09-28 08:41 UTC, Bidway commented on trunk/ii02313/task_01/src/otis_1.cpp
В данной строчке кода :
double next = a * prev - prev * prev * b + u * c + d * sin(u);
Необходимо использовать как y(t), так и y(t-1), а ты используешь только prev

2023-09-29 21:11 UTC, sosiska52 commented on trunk/ii02313/task_01/src/otis_1.cpp
Функции названы по номерам уравнений из задания

2023-10-17 08:58 UTC, idzm requested changes
Также добавить факт выполнения задания в общий файл - https://github.com/brstu/OTIS-2023/edit/main/readme.md#L29-29.

2023-10-19 05:54 UTC, idzm approved these changes

2023-10-19 05:54 UTC, merged