[task_03] Add Solution
brstu/OTIS-2023 pull request #168
Opened 2023-11-25 22:11 UTC by SukharevichDmitry

2023-12-06 06:35 UTC, idzm approved these changes

2023-12-06 06:37 UTC, idzm requested changes
Необходимо исправить замечания от платформы `Codacy`.

2023-12-12 05:55 UTC, idzm requested changes

2023-12-12 05:55 UTC, idzm commented on .idea/.gitignore
Необходимо удалить данный файл из запроса.

2023-12-12 05:55 UTC, idzm commented on .idea/.name
Необходимо удалить данный файл из запроса.

2023-12-12 05:55 UTC, idzm commented on .idea/OTIS-2023.iml
Необходимо удалить данный файл из запроса.

2023-12-12 05:55 UTC, idzm commented on .idea/inspectionProfiles/profiles_settings.xml
Необходимо удалить данный файл из запроса.

2023-12-12 05:55 UTC, idzm commented on .idea/misc.xml
Необходимо удалить данный файл из запроса.

2023-12-12 05:55 UTC, idzm commented on .idea/modules.xml
Необходимо удалить данный файл из запроса.

2023-12-12 05:55 UTC, idzm commented on .idea/vcs.xml
Необходимо удалить данный файл из запроса.

2023-12-12 07:47 UTC, SukharevichDmitry commented on .idea/vcs.xml
Удалил.

2023-12-12 07:47 UTC, SukharevichDmitry commented on .idea/modules.xml
Удалил.

2023-12-12 07:48 UTC, SukharevichDmitry commented on .idea/misc.xml
Удалил.

2023-12-12 07:48 UTC, SukharevichDmitry commented on .idea/inspectionProfiles/profiles_settings.xml
Удалил.

2023-12-12 07:48 UTC, SukharevichDmitry commented on .idea/OTIS-2023.iml
Удалил.

2023-12-12 07:48 UTC, SukharevichDmitry commented on .idea/.name
Удалил.

2023-12-12 07:48 UTC, SukharevichDmitry commented on .idea/.gitignore
Удалил.

2023-12-13 19:24 UTC, merged