[task_05] Add Solution
brstu/OTIS-2023 pull request #181
Opened 2023-11-28 06:48 UTC by EuZireael

2023-12-08 15:17 UTC, Gomziakoff commented
Изменения в readme.md должны затрагивать только собственные данные

2023-12-12 06:02 UTC, idzm requested changes

2023-12-12 06:02 UTC, idzm commented on readme.md
Изменения в данном файле должны затрагивать только данные автора.

2023-12-12 06:02 UTC, idzm commented
Запрос закрыт из-за отсутствия активности.

2023-12-12 06:02 UTC, closed without merging