[task_02] Add problem solution
brstu/OTIS-2023 pull request #19
Opened 2023-10-16 16:58 UTC by alkurash

2023-10-19 06:15 UTC, idzm requested changes
Необходимо убрать из запроса добавление ненужных файлов, изменение глобального файла CMakeLists.txt.
Также добавить факт выполнения задания в общий файл - https://github.com/brstu/OTIS-2023/edit/main/readme.md#L52-52.

2023-10-24 05:44 UTC, idzm requested changes

2023-10-24 05:44 UTC, idzm commented on trunk/ii02408/task_02/doc/report.md
> +1. Написать отчет по выполненной лабораторной работе №1 в .md формате (readme.md) и с помощью запроса на внесение изменений (**pull request**) разместить его в следующем каталоге: **trunk\ii0xxyy\tas
Это отчёт по второй или первой лабораторной работе?

2023-10-27 08:49 UTC, alkurash commented on trunk/ii02408/task_02/doc/report.md
> +1. Написать отчет по выполненной лабораторной работе №1 в .md формате (readme.md) и с помощью запроса на внесение изменений (**pull request**) разместить его в следующем каталоге: **trunk\ii0xxyy\tas
по второй

2023-10-27 08:50 UTC, alkurash commented on trunk/ii02408/task_02/doc/report.md
> +1. Написать отчет по выполненной лабораторной работе №1 в .md формате (readme.md) и с помощью запроса на внесение изменений (**pull request**) разместить его в следующем каталоге: **trunk\ii0xxyy\tas
файл изменил

2023-11-02 06:20 UTC, idzm submitted a review, later dismissed

2023-11-09 08:11 UTC, idzm approved these changes

2023-11-09 08:11 UTC, merged