[task_03] Add problem solution
brstu/OTIS-2023 pull request #253
Opened 2023-12-07 09:36 UTC by arciomwww

2023-12-13 17:40 UTC, alkurash requested changes
файл trunk/ii02303/task_03/.gitignore не должен присутствовать в работе

2023-12-13 18:43 UTC, alkurash approved these changes

2023-12-14 05:57 UTC, Gomziakoff approved these changes

2023-12-14 06:23 UTC, idzm requested changes

2023-12-14 06:23 UTC, idzm commented on trunk/ii02303/task_03/main.cpp
Кодировка файла должна быть utf-8.

2023-12-14 06:52 UTC, idzm submitted a review, later dismissed

2023-12-14 07:31 UTC, Bidway approved these changes

2023-12-14 07:34 UTC, Gomziakoff approved these changes

2023-12-14 07:57 UTC, Gomziakoff approved these changes

2023-12-14 08:01 UTC, Gomziakoff approved these changes

2023-12-14 08:03 UTC, Bidway approved these changes

2023-12-14 08:24 UTC, LapinVladimir approved these changes

2023-12-14 08:25 UTC, VolkogonNikita approved these changes

2023-12-15 17:08 UTC, idzm approved these changes

2023-12-15 17:09 UTC, merged