[task_03] Add problem solution
brstu/OTIS-2023 pull request #254
Opened 2023-12-07 09:41 UTC by Gomziakoff

2023-12-08 15:00 UTC, Gomziakoff commented
По неизвестной мне причине, sonarcloud отказывается проверять проекты написанные на QT в папке src, а в папке задания проверяет. Поэтому задание не помещено в папку src, прошу простить.

2023-12-12 20:53 UTC, VolkogonNikita submitted a review, later dismissed

2023-12-13 18:32 UTC, alkurash submitted a review, later dismissed

2023-12-14 06:25 UTC, idzm requested changes

2023-12-14 06:25 UTC, idzm commented on trunk/ii02320/task_03/CMakeLists.txt.user
Данный файл не должен содержаться в запросе.

2023-12-14 06:25 UTC, idzm commented on trunk/ii02320/task_03/CMakeLists.txt.user.e444c4c
Данный файл не должен содержаться в запросе.

2023-12-14 06:28 UTC, Gomziakoff commented on trunk/ii02320/task_03/CMakeLists.txt.user
Исправлено

2023-12-14 06:49 UTC, idzm submitted a review, later dismissed

2023-12-14 06:51 UTC, merged