[task_05] Add problem solution
brstu/OTIS-2023 pull request #26
Opened 2023-10-20 21:33 UTC by Gomziakoff

2023-10-24 06:09 UTC, idzm requested changes

2023-10-24 06:09 UTC, idzm commented on trunk/ii02320/task_05/doc/report.md
> +При выполнении 4 лабораторной работы столкнулся с ошибкой в проекте NIKA на странице sc-web (localhost:8000), о чем и сообщил в репозитории проекта: https://github.com/ostis-apps/nika/issues/300
Необходимо внести следующие исправления:
1. Разделить вопрос на два (первый - лишняя кнопка в интерфейсе, второй - с превышением длины пути). Здесь работает такое же правило, как и в запросе на внесение изменений (pull request) - **один** запрос на решение **одной** задачи - **один** вопрос об **одной** найденной ошибке.
2. Необходимо использовать форматирование:

На [картинке](https://user-images.githubusercontent.com/88232005/277053646-9023d24f-8419-4dd0-8a56-a025eb856664.png) видно, что в интерфейсе присутствует лишняя кнопка - кнопки идентичны. Также в гайде установки слишком мало информации об установке, у меня в процессе установки возникла проблема с преувеличением длины пути:

> error: unable to create file ims/ostis_tech/lib_ostis/sectn_lib_of_reusable_comp_ui/ui_menu/Methods_evaluation/Kb_volume_metrics/ui_menu_file_for_calculation_average_depth_of_subject_domain/lib_component_ui_menu_file_for_calculation_average_depth_of_subject_domain.scs: Filename too long

Для решения этой проблемы достаточно использовать команду `git config --system core.longpaths true`, эта проблема забрала у меня немало времени.

2023-10-24 17:23 UTC, Gomziakoff commented on trunk/ii02320/task_05/doc/report.md
> +При выполнении 4 лабораторной работы столкнулся с ошибкой в проекте NIKA на странице sc-web (localhost:8000), о чем и сообщил в репозитории проекта: https://github.com/ostis-apps/nika/issues/300
Разделил и добавил форматирование

2023-11-02 06:25 UTC, idzm requested changes
Также необходимо добавить факт выполнения задачи в общий файл с успеваемостью.

2023-11-02 07:59 UTC, Gomziakoff commented
Отметил выполнение задачи в успеваемости

2023-11-09 08:13 UTC, idzm approved these changes

2023-11-09 08:14 UTC, merged