[task_04] Add problem solution
brstu/OTIS-2023 pull request #270
Opened 2023-12-10 15:05 UTC by Katty-Bisha

2023-12-12 07:06 UTC, idzm requested changes
Необходимо также отразить факт выполнения работы в `readme.md`.

2023-12-12 20:50 UTC, VolkogonNikita approved these changes

2023-12-13 18:37 UTC, alkurash submitted a review, later dismissed

2023-12-19 05:46 UTC, idzm approved these changes

2023-12-19 05:47 UTC, merged