[task_01] Add Solution
brstu/OTIS-2023 pull request #286
Opened 2023-12-12 07:48 UTC by idterk

2023-12-12 07:57 UTC, idterk commented
В ноябре закидывал данную лабораторную работу, исправил ошибки. Неделю назад подходил к вам на занятии, вы говорили что скорее всего случайно закрыли. Перезалил

2023-12-12 20:44 UTC, VolkogonNikita requested changes
Запрос не должен содержать изменения, связанные с работой №4 и работой №2

2023-12-14 05:30 UTC, Gomziakoff requested changes
Необходимо оставить изменения касающиеся только 1 лаб. Работы

2023-12-14 06:44 UTC, idterk commented
> Запрос не должен содержать изменения, связанные с работой №4 и работой №2

Исправил

2023-12-14 06:45 UTC, idterk commented
> Необходимо оставить изменения касающиеся только 1 лаб. Работы

Исправил

2023-12-14 07:53 UTC, closed without merging