[task_02] Add problem solution
brstu/OTIS-2023 pull request #319
Opened 2023-12-12 14:13 UTC by hudshiy1

2023-12-12 14:30 UTC, VolkogonNikita approved these changes

2023-12-14 07:05 UTC, LapinVladimir approved these changes

2023-12-15 20:34 UTC, Gomziakoff requested changes
необходимо отобразить выполнение задания в ридми

2023-12-16 05:35 UTC, Gomziakoff approved these changes

2023-12-16 08:03 UTC, VolkogonNikita approved these changes

2023-12-17 14:15 UTC, LapinVladimir approved these changes

2023-12-17 14:36 UTC, Bidway approved these changes

2023-12-17 14:36 UTC, merged