[task_04] Add problem solution
brstu/OTIS-2023 pull request #379
Opened 2023-12-16 12:17 UTC by Gluharev-Danik

2023-12-17 15:21 UTC, VolkogonNikita approved these changes

2023-12-17 20:39 UTC, Gomziakoff approved these changes

2023-12-18 13:30 UTC, LapinVladimir approved these changes

2023-12-19 09:30 UTC, Bidway approved these changes

2023-12-20 19:11 UTC, VolkogonNikita requested changes
а де решение

2023-12-21 16:49 UTC, Gluharev-Danik reviewed
Добавил изменения

2023-12-21 19:52 UTC, closed without merging