[task_01] Add solution
brstu/OTIS-2023 pull request #41
Opened 2023-10-31 08:41 UTC by MsharVladislav

Add solution

2023-10-31 22:05 UTC, MsharVladislav commented
Improved code

2023-11-02 06:34 UTC, idzm requested changes
Также необходимо добавить факт выполнения задачи в общий файл с успеваемостью.

2023-11-02 06:35 UTC, idzm requested changes
Также необходимо добавить факт выполнения задачи в общий файл с успеваемостью.

2023-11-09 08:23 UTC, idzm approved these changes

2023-11-09 08:25 UTC, merged