[task_02] Add Solution
brstu/OTIS-2023 pull request #58
Opened 2023-11-02 20:41 UTC by SukharevichDmitry

2023-11-09 08:53 UTC, idzm requested changes
Необходимо отразить выполнение работы в файле ``readme.md`` в соответствующей строке (например, для студента под порядковым номером 1 - https://github.com/brstu/OTIS-2023/edit/main/readme.md?#L17-L17).

2023-11-16 06:15 UTC, idzm requested changes
> Необходимо отразить выполнение работы в файле `readme.md` в соответствующей строке (например, для студента под порядковым номером 1 - https://github.com/brstu/OTIS-2023/edit/main/readme.md?#L17-L17).

2023-11-28 06:04 UTC, idzm requested changes

2023-11-28 06:04 UTC, idzm commented on trunk/ii02418/task_02/doc/readme.md
Файл отчета не должен быть пустым.

2023-11-29 19:12 UTC, SukharevichDmitry commented on trunk/ii02418/task_02/doc/readme.md
> Файл отчета не должен быть пустым.

Исправил.

2023-12-05 05:48 UTC, idzm approved these changes

2023-12-05 05:49 UTC, merged