Task1
brstu/OTIS-2023 pull request #69
Opened 2023-11-08 16:20 UTC by IvanBaranchuk

2023-11-16 06:25 UTC, idzm requested changes
Необходимо отразить выполнение работы в файле readme.md в соответствующей строке (например, для студента под порядковым номером 1 - https://github.com/brstu/OTIS-2023/blob/main/readme.md?plain=1#L20).

2023-11-17 15:26 UTC, IvanBaranchuk commented
> Необходимо отразить выполнение работы в файле readme.md в соответствующей строке (например, для студента под порядковым номером 1 - https://github.com/brstu/OTIS-2023/blob/main/readme.md?plain=1#L20).

Добавил

2023-11-28 06:12 UTC, idzm approved these changes

2023-12-05 05:52 UTC, idzm approved these changes

2023-12-05 05:53 UTC, merged